name: Swift Linux build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, next ]

jobs:
  build-linux:
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        swift: ["5.9"]


    runs-on: ${{ matrix.os }}
    steps:
    - uses: fwal/setup-swift@v1
      if: ${{ false }}
      with:
        swift-version: ${{ matrix.swift }}

    - uses: actions/checkout@v3    
      with:
        submodules: 'true'

    - name: Start consul
      uses: ./.github/actions/consul-start

    - name: Ubuntu deps
      if: ${{ runner.os == 'Linux' }}
      run: |
        sudo apt-get install -y libjemalloc-dev libsasl2-dev libcurl4-openssl-dev

    - name: Swift version
      run: swift --version

    - name: Run tests
      continue-on-error: true
      run: docker-compose -f docker/docker-compose.yaml -f docker/docker-compose.2204.59.yaml run test
