name: Swift check API breaks

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]

jobs:
  analyze-api-breakage:

    runs-on: [ubuntu-latest]
    timeout-minutes: 30
 
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: 'true'

    - name: Ubuntu deps
      if: ${{ runner.os == 'Linux' }}
      run: |
        sudo apt-get install -y libjemalloc-dev libsasl2-dev libcurl4-openssl-dev
    - name: Build
      run: swift build
    - name: Analyze API breakage
      run: swift package diagnose-api-breaking-changes origin/next
